# Generated by Django 4.2.7 on 2023-11-20 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, verbose_name='место')),
                ('time', models.CharField(max_length=20, verbose_name='время')),
                ('action', models.TextField(verbose_name='действие')),
                ('is_pleasurable', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('period', models.IntegerField(default=1, verbose_name='периодичность (в днях)')),
                ('prize', models.CharField(blank=True, max_length=100, null=True, verbose_name='вознаграждение')),
                ('lead_time', models.PositiveIntegerField(verbose_name='время на выполнение')),
                ('public', models.BooleanField(default=True, verbose_name='признак публичности')),
                ('associated_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='связанная привычка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
