# Generated by Django 4.2.7 on 2023-11-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='is_pleasurable',
            field=models.BooleanField(default=True, verbose_name='признак приятной привычки'),
        ),
    ]
