# Generated by Django 4.2.7 on 2023-11-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_is_pleasurable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='is_pleasurable',
            field=models.BooleanField(default=False, verbose_name='признак приятной привычки'),
        ),
    ]
