# Generated by Django 4.2.7 on 2023-11-21 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_is_pleasurable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='время'),
        ),
    ]
